services:
  postgresql_db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - 01_exercices_psql_data:/var/lib/postgresql/data

volumes:
  01_exercices_psql_data: