services:
  postgresql_db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_training_data:/var/lib/postgresql/data

volumes:
  postgres_training_data: